version: "3"

networks:
  test-network:
    name: test-network

services:
  db:
    image: postgres:alpine
    container_name: test-postgres
    networks:
      - dev-network
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test-pwd
      POSTGRES_DB: test
      PGUSER: test
    ports:
      - "5432:5432"
    volumes:
      - ./:/mnt/script/
  